services:
  postgres:
    image: postgres:15-alpine
    container_name: kanban_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: kanbandb
    ports:
      - "5439:5432"